name: CLA 🔏

on:
  issue_comment:
    types:
      - created
  # For PRs that originate from forks
  pull_request_target:
    types:
      - opened
      - closed
      - synchronize

jobs:
  CLA:
    name: CLA 📝
    runs-on: ubuntu-latest
    # ⭐ 添加权限配置
    permissions:
      contents: write
      pull-requests: write
      issues: write
    uses: insightsengineering/.github/.github/workflows/cla.yaml@main
    secrets: inherit
